version: 2.1

workflows:
  # Only 1 workflow needed. Runs jobs listed in this file
  maven_test:
    jobs:
      - unit_test
      - integration_test:
          requires:
            - unit_test
      - hold:
          type: approval
          requires: 
            - integration_test
      - deploy:
          requires:
            - hold

executors:
  # Specifying executor to run jobs
  doc:
    docker:
      - image: cimg/openjdk:11.0

jobs:
  # Job to build the project
  unit_test:
    executor: doc
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn package
      - persist_to_workspace:
         root: ~/repo/
         paths:
           - tmp/
      - store_artifacts:
            path:  target/Job-Matching-System-1.0.jar
      - store_artifacts:
            path:  target/site/jacoco/
      - store_artifacts:
            path:  target/surefire-reports

  # Job to carry out unit and integration tests and store Artifacts to circleCi
  integration_test:
      executor: doc
      steps:
        - checkout
#        - attach_workspace:
#            at: ./target
        - run:
            name: Tests
            command: mvn -Dmaven.test.skip=true verify

  # Deploy artifacts to Artifactory repo
  deploy:
    executor: doc
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp/
      - run:
          name: Compress Artifacts to TAR
          command: |
            tar -cvzf BUILD_NUM.tar target/
      - store_artifacts:
          path: BUILD_NUM.tar
          destination: target/BUILD_NUM.tar
      - run:
          name: Uploading TAR to Artifactory Repo
          command: curl -H "X-JFrog-Art-Api:$ARTIFACTORY_APIKEY" -T BUILD_NUM.tar "https://rmrartifact.jfrog.io/artifactory/rmrmaven-libs-release-local/$CIRCLE_BUILD_NUM/TAR/$CIRCLE_BUILD_NUM-BUILD.tar"
#      - run: mvn dependency:go-offline
#      - run:
#          name: Maven Build
#          command: |
#            mvn clean install
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh 
      - run:
          name: Push To Artifactory
          command: |
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --apikey $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog rt u "tmp/target/*.jar" rmrmaven-libs-release-local/$CIRCLE_BUILD_NUM/ --build-name="test_build3" --build-number=$CIRCLE_BUILD_NUM --flat=false
            ./jfrog rt u "tmp/target/site/jacoco/ie.gmit/" rmrmaven-libs-release-local/$CIRCLE_BUILD_NUM/site/jacoco/ie.gmit/
            ./jfrog rt u "tmp/target/surefire-reports/" rmrmaven-libs-release-local/$CIRCLE_BUILD_NUM/surefire-reports/
            ./jfrog rt u "tmp/target/" rmrmaven-libs-release-local/$CIRCLE_BUILD_NUM/$CIRCLE_BUILD_NUM-BUILD.zip --archive zip
            ./jfrog rt bce "test_build3" $CIRCLE_BUILD_NUM
            ./jfrog rt bp "test_build3" $CIRCLE_BUILD_NUM

