version: 2.1

workflows:
  # Only 1 workflow needed. Runs jobs listed in this file
  maven_test:
    jobs:
      - clean
      - unit_tests:
          requires:
            - clean
      - integration_test:
          requires:
            - unit_tests
      - deploy:
          requires:
           - integration_test

executors:
  # Specifying executor to run jobs
  doc:
    docker:
      - image: cimg/openjdk:11.0


jobs:
  # Job to clean project before testing
  clean:
    executor: doc
    steps:
      - checkout
      - run:
          name: Clean
          command: mvn clean
  # Job to run unit tests
  unit_tests:
      executor: doc
      steps:
        - checkout
        - run:
            name: Unit Tests
            command: mvn package
  # Job to run the integration test
  integration_test:
      executor: doc
      steps:
        - checkout
        - run:
            name: Integration Test
            command: mvn verify
        # Storing some results as artifacts to be viewable in CircleCI
        - store_artifacts:
            path:  target/site/jacoco
        - store_artifacts:
            path:  target/surefire-reports
  # Job to deploy artifacts
  deploy:
     executor: doc
     steps:
        - checkout
        # Storing some results as artifacts to be viewable in CircleCI
        - store_artifacts:
            path:  target/practiceMaven2-1.0-SNAPSHOT.jar
        - store_artifacts:
            path:  target/site/jacoco
        - store_artifacts:
            path:  target/surefire-reports
        - attach_workspace:
            at: ./artifacts
        - run:
            name: "Publish Release on GitHub"
            command: |
              VERSION=$(my-binary --version)
              ghr -t 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 -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
  # Job to merge with master
#  merge:
#      executor: doc
#     steps:
#        - checkout
#        - run:
#            name: Merge
#            command: git checkout master ; git merge << pipeline.git.branch	 >>