version: 2.1

workflows:
  # Only 1 workflow needed. Runs jobs listed in this file
  maven_test:
    jobs:
      - clean
      - build:
          requires:
            - clean

executors:
  # Specifying executor to run jobs
  doc:
    docker:
      - image: cimg/openjdk:11.0

jobs:
  # Job to clean project before testing
  clean:
    executor: doc
    steps:
      - checkout
      - run:
          name: Clean
          command: mvn clean
  # Job to build and deploy the project
  build:
      executor: doc
      working_directory: ~/repo
      steps:
        - checkout
        - run:
            name: Integration Test
            command: mvn verify
        # Storing some results as artifacts to be viewable in CircleCI
        - store_artifacts:
            path:  target/Job-Matching-System-1.0.jar, target/artifacts/Job-Matching-System-1.0.jar
        - store_artifacts:
            path:  target/site/jacoco/ie.gmit, target/artifacts/site/jacoco/ie.gmit
        - store_artifacts:
            path:  target/surefire-reports, targets/artifacts/surefire-reports
        - run:
            name: Compress Artifacts
            command: tar -cvzf BUILD_NUM.tar target/artifacts/
        - store_artifacts:
            path: target/artifacts/BUILD_NUM.tar
            destination: target/artifacts/BUILD_NUM.tar
        - run: mvn dependency:go-offline
        - run:
            name: maven build
            command: |
              mvn clean install
        - run:
            name: Install jFrog CLI
            command: curl -fL https://getcli.jfrog.io | sh
        - run:
            name: Push To Artifactory
            command: |
              ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --apikey $ARTIFACTORY_APIKEY --interactive=false
              ./jfrog rt u "target/" "rmrmaven-libs-release-local" --build-name="test_build3" --build-number=$CIRCLE_BUILD_NUM --flat=false
              ./jfrog rt bce "test_build3" $CIRCLE_BUILD_NUM
              ./jfrog rt bp "test_build3" $CIRCLE_BUILD_NUM

