version: 2.1

workflows:
  # Only 1 workflow needed. Runs jobs listed in this file
  maven_test:
    jobs:
      - clean
      - unit_tests:
          requires:
            - clean
      - integration_test:
          requires:
            - unit_tests
      - store_circleci:
          requires:
            - integration_test
      - upload-artifact:
          requires:
            - integration_test

executors:
  # Specifying executor to run jobs
  doc:
    docker:
      - image: cimg/openjdk:11.0

jobs:
  # Job to clean project before testing
  clean:
    executor: doc
    steps:
      - checkout
      - run:
          name: Clean
          command: mvn clean
  # Job to run unit tests
  unit_tests:
      executor: doc
      steps:
        - checkout
        - run:
            name: Unit Tests
            command: mvn package
  # Job to run the integration test
  integration_test:
      executor: doc
      steps:
        - checkout
        - run:
            name: Integration Test
            command: mvn verify
  # Job to store artifacts in CircleCI
  store_circleci:
     executor: doc
     steps:
        - checkout
        # Storing some results as artifacts to be viewable in CircleCI
        - store_artifacts:
            path:  target/Job-Matching-System-1.0.jar
        - store_artifacts:
            path:  target/site/jacoco
        - store_artifacts:
            path:  target/surefire-reports
  # Job to upload artifacts to Artifactory
  upload-artifact:
    executor: doc
    working_directory: ~/repo
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: maven build
          command: |
            mvn clean install
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push To Artifactory
          command: |
            ./jfrog config add --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --apikey $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog rt u "multi*/*.jar" "rmrmaven-maven-jcenter" --build-name="test_build" --build-number=$CIRCLE_BUILD_NUM --flat=false
            ./jfrog rt bce "test_build" $CIRCLE_BUILD_NUM
            ./jfrog rt bp "test_build" $CIRCLE_BUILD_NUM